workflows:
  check-env-vars:
    name: hello world
    environment:
      groups:
        - TEST
    scripts: 
      - name: Check env vars
        script: |
          echo "Hello World!" 
          printenv